version: 2
updates:
  - package-ecosystem: "npm"
    directory: /app
    target-branch: "hotfix/dependabot"
    open-pull-requests-limit: 10
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: .github/
    target-branch: "hotfix/dependabot"
    open-pull-requests-limit: 10
    schedule:
      interval: daily